/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "json-server.dev",
        pathname: "/ai-profiles/**",
      },
    ],
  },
};

export default nextConfig;

// Generated by AI
